name = "MatrixCorrectionTools"
uuid = "41f81499-25de-46de-b591-c3cfc21e9eaf"
authors = ["Bagaev Dmitry <d.v.bagaev@tue.nl>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
